/**
 * FINDING-4 — the bundled consortium roster (sovereign-node REDUNDANCY invariant).
 *
 * This is the signed list of the sovereign directory nodes that make up the CELLO consortium,
 * COMPILED INTO the client. It is loaded by default (when the operator does not override it via
 * CELLO_CONSORTIUM_MANIFEST) so that a cold-boot daemon already knows every directory — and can
 * fail over to a reachable one — even when its configured/primary directory is unreachable. Without
 * a bundled roster the failover resolver has nothing to route to (the exact FINDING-4 gap: the
 * roster-aware dialer was correct but the roster was empty), so a single directory being down
 * stranded the client at startup, violating the redundancy invariant.
 *
 * Trust model:
 *   - The manifest is threshold-signed by the consortium officer key(s). At load the client
 *     RE-VERIFIES it against BUNDLED_CONSORTIUM_ROOT_KEYS (a self-consistency / anti-corruption
 *     gate — the manifest and root keys ship together, so this catches a bad regeneration, not a
 *     network adversary).
 *   - The node `pubkey`s are the directories' Ed25519 node keys. They are the trust anchor for
 *     step-6 directory identity auth (M7-MANIFEST-002): when the client connects to (or fails over
 *     to) a directory, the directory must sign the client's challenge with the matching node key,
 *     proving it is the real consortium node for that nodeId — defeating a MITM on the plaintext
 *     /bootstrap that would otherwise redirect the client to a rogue directory. THIS is the
 *     adversarial defense; it is enabled by default alongside the roster.
 *
 * nodeId MUST equal the directory's reported NODE_ID (`<cloud>-<region>`, e.g. `gcp-use1`); the step-6 verifier
 * looks the node up by nodeId. pubkey MUST equal the node's own Ed25519 signing key, which the
 * regeneration script below reads from GCP Secret Manager (`cello-<nodeId>-node-key`) rather than
 * being transcribed. endpoint is the HTTP /bootstrap base, and MUST be the node's ADDRESS — see
 * PRODUCTION_DIRECTORY_URL in directory-bootstrap.ts for why a hostname here disables step-6.
 *
 * Regeneration: on directory node-key or officer-key rotation, re-sign with
 * `infra/scripts/sign-gcp-consortium-manifest.mjs` (in the trustless-cello repo) and update this
 * constant + both root sets below. The officer signing keys live in GCP Secret Manager as
 * `cello-consortium-officer-key-0` (Ed25519) and `cello-consortium-officer-mldsa-key-0` (ML-DSA-44,
 * M9D 004); only their PUBLIC keys are embedded here.
 *
 * Crypto reference: RFC 8032 (Ed25519) and FIPS 204 (ML-DSA-44) — BOTH signature sets are verified
 * by verifyManifest, and both are required.
 */

import type { ConsortiumManifestInput } from "@cello-protocol/crypto";

/** The signed consortium manifest (roster of sovereign directory nodes). */
export const BUNDLED_CONSORTIUM_MANIFEST: ConsortiumManifestInput = {
  // ── v4, signed post-quantum (M9D 004-PQNODEKEYS, 2026-09-30) ───────────────────────────────
  // Every node names its ML-DSA-44 key (`mldsa_pubkey`), the manifest names the portal's ML-KEM-768
  // intake key (`mlkem_intake_key`, same key_id as `intake_key`), and `pq_signatures` sits beside
  // `signatures` over the same body. Every other field is byte-identical to v3 (the TLS cutover,
  // 2026-09-10: HTTPS endpoints on each region's own balancer, `/dns4/…/tcp/443/tls/ws` multiaddrs).
  //
  // 🔴 THIS ROSTER AND THE ONE THE NODES SERVE MUST CARRY THE SAME ENDPOINTS. The daemon builds its
  // directory-identity challenge verifier ONLY when the resolved directory URL matches one of the
  // endpoints BELOW. If the fleet serves a name this file does not list, step 6 does not fail — it
  // is skipped, silently, on every connect and reconnect, and step 6 is what turns a /bootstrap
  // MITM into a refused connection rather than a successful impersonation.
  //
  // `version` is a MONOTONICITY GATE, not a schema number: the daemon persists the highest version
  // it has seen and rejects anything lower as a rollback. A daemon carrying this v4 refuses a fleet
  // still serving v3 — which is why this ships with 010-PQROLL, and why it must only ever increase.
  //
  // Generated by trustless-cello/infra/scripts/sign-gcp-consortium-manifest.mjs. Do NOT hand-edit
  // a field: the signatures cover every one of them and an edited copy verifies against nothing.
  version: 4,
  not_before: "2026-01-01T00:00:00Z",
  expires: "2030-01-01T00:00:00Z",
  nodes: [
    {
      nodeId: "gcp-use1",
      pubkey: "7969e22a7d95293ae343cb2667c2a4d7127aa8748478582fa637674c30e0113c",
      mldsa_pubkey:
        "80e51c33440c70d5f042520537ab2999a5376d72bffac24e1fef04d6978cc98a27c144ec218791e4002686d030862a47"
        + "533c4b0c35078459364b64d2c22952136dcc801bfb0a4e2398fb7d8618f52d8acdda45594229ed5e8c728a03858c3873"
        + "bf1203c35676f62b88eb40b18265a707c62929817bbb6e85c05f307fcc807dece488333eed249d72842739a41b6a50c9"
        + "010d0dc562ab3589dbefacc9b1d1ea78a9b958afa0c600ae804619d4d215918f2de2792ea9a11e564a11f667ac8bdef4"
        + "fb8d34bff69e597d1aa2f35cdd1337cf18468ab7946409238677a7131aee87efbc880cc848ed24f33ec88b2265991797"
        + "7621a699906335b6ff8d53a783ea40b5f870334653221f3484a5fd854873c335ea04d6b9a2e5b9bc72ad25df4d9b3ef2"
        + "100fc56c1374da5a4b839301544ec0a254da16cd105971f5bcb6c032430cf084f4c48b3fdf3975bcb7e05be515a136d8"
        + "dea7cd5fb83f22eaf9534289437c5de3e0987877204821a1dad3b0f29c36e79945a330aaa05a9fa02a730b3d2db4c6d9"
        + "13ed23c134084874e6d3957e502387d02b29221f5a9d8b0dd5d51b940dde78397bf9e2d0a8b1cf4f3d790849a1f6f03c"
        + "b582b68f53158d328a7ff20b386d10d8ac9cc4b0069c9121a0cd7e243e0af730f68cff2fb779a76c11cd4855642f519c"
        + "e222e6bf77581c4f77352644c78c6ff14972f6a6f1167937387e225abf9530d2aae80c7a1d9ae45a5b3cad95eb3a7234"
        + "1b79178af5a90a0eeadb84b0fcb7e1ac70632415ff82f5d8a54927d40e194be89e09675aa1c1651152f83335f45a6f5b"
        + "f9bb57e5498a597ca61bb5fb6ee95bdeb1156d2065b40f4abc3f0e4c276c1639ebf41e3e1772f4a12922eb5ead90f7bd"
        + "07398e63b5e5905467dc5c310d6fdbf436da0ceb92976ebcedd6cdc2a0f4e06628922622623f975be199c8c7d5baa666"
        + "4d3bcfa0d3b301de069c7dd0e609ebf2d4b5f43eec6aca36f9b6ea8aa3a46577389229cfcc5abe26ea7e9f351dd5b19f"
        + "6bf1d244485932d000752d263e44f346829267f96107d9cb14f1a284dd7f28879cf42f2f8a8140b2b71ed594d5b36be9"
        + "d786289a3dce76d18ec45aade527c97a9565b097aa9627af8d2b90e6931c2aa1b96e6c0ff61584777d734e79b1c6b819"
        + "cf4dbfe3ed49068f8c424980542e68abed9d0b5ce77188423af6d4ae6967b39813559bca28b6a6f73e10c12fb528c1de"
        + "c1ef4fa147a6414b2bdd9ad94a046e996c6cc2768dbf7ccd167febbf8c5d8c19412735fc025639381d7ae1ec718956fb"
        + "4dbfdd7a70da7f1282afcee227b2b5bb758e6d496dba91a27e014a110735448e61fc208831c59288ced0dbfa8f089c51"
        + "69c3f0f729965b29c2021521fc9df4bb689a33acd74c89e3f80765d672da0b277bfb27af65f892d2c19e0e279182ebf4"
        + "f638716765bcac720bb454c21c7d638691186d94354c8873f9a1848b471624aaac48c30eb786a248941ce9e9b0aba405"
        + "ca2060ac7af1b71f15f34f2867b2cbdc5f667e00bc197de5811b98af289e9da30accd6eed5593e143e11ec9541d3194b"
        + "58a7ac0104abca070506babece9894f5f268e698fae3c7e0f9308e0df82d6397c176125cf8e4a1798c82c0b41e77c63f"
        + "641b3f4f2b9ee8912c2f384dca77d4487c57671be9dd9fdc18e9f0ccfa7616c197b9316985d2c1dc21c8f59aaf93609f"
        + "f66a33b8d9fce41eff2abf287fd0ea830f8d38d0675c4c717f3cce1bdf005186312e58651bd85226d7c65f6d677aff33"
        + "9f269887479fc3c919ab1268d12b679fbf378a434dc0a5b98da275196ed8c04ff8cd06d8feca011c8d0319721671800b"
        + "5c3b27dafb16cceb5107118f66c6ac75",
      region: "use1",
      provider: "gcp",
      endpoint: "https://directory-use1.cello.mygentic.ai",
      peerId: "12D3KooWMH58hm8xpuwgwaNSvnvXBuc126jfuUMVbrGNcU2MeEAX",
      multiaddr: "/dns4/directory-use1.cello.mygentic.ai/tcp/443/tls/ws",
      role: "validator",
    },
    {
      nodeId: "gcp-usc1",
      pubkey: "ef961384100bb087f36b68e3a270acb8f22fdf62c4cd5e517e423afb7f399002",
      mldsa_pubkey:
        "07f225e1f9499396aa17da3a424174a86f1e32c0cf9916a0b2680d30990b06dcb30ec1aa3f0265f985699141a2f5d1f5"
        + "a1c925810a70cf20bfb9fc3b22b6c8ec01ded06768bd958da21a40ea89b32b1964bf80e4bbfc0495f64441d7484cfbc7"
        + "08cb4ffcc8b8aad54c233e50ac32ccc9645c620fc0ddff8a0207e65241dd4bac055c2f44d3705c3435290bc62ad2b6a9"
        + "b6ead44d8251b41b5629a2dac2fd18f1568988dfc0e56546e63630cc0fd41267c808ccb6290a3072b969cf9fb9f066f1"
        + "72ab696504eaeaeac6bb9ea751197544a6382f190153b0d0e9529c2768f6a653f03260a2aa736ee151e125e4b81fd11c"
        + "901938b5615aa79ab1e368ea5e5cae2da9279a4023543c088601cdeddd6c59f76b7e18cd6e872189e8809a623bc82b03"
        + "00c1e172d2804702204339afd18f8c1ab015347ce1e0d354c2dd3ca4f87b79747af9c5faa9bd7eabc56545d15106c3c6"
        + "507c88b3380015bf68505288c4c23d1ed2fc23f74f68ac1d25dee8ee89495ad8a12812f267e686afeb4edc257bcf0a19"
        + "676280864934a377dddbbbebaf0b6d1402a4264f9d51c4d0eb6f4cbd4146e8f0b45c68b22f0926ea8c23eae102a4edbb"
        + "5e5df29d4f33cbdbd2f2465b0d642e7db8316b09298ba2cd48252b0d9c4650e79346cf47b34cb67a0a07e638e97c8763"
        + "ce5e17d296ae3b60b8fe18b484046f1334ee0d53c527d21afcc5bbc9892a74db23f78d6145de0c161dcfb7e2974fa989"
        + "a682464cf452ac3671e36441db213727dfa627888d3f3648a12bdd51b08b54622a53a4dce9d64e686f4bf34279695db8"
        + "35f88f6fa70f13bb6e496355b69e55604988a368e52cd0e1ea7f8755595bd551f38c7e75b4061d26269c22c857592a2b"
        + "ad8c93033f12b71b8d06222de674fa56fc8b75fefc9e5665a243be7eeb474422e10f1d674d8f2a663d9a70206149cd61"
        + "e80fe9a5b09a8a7b696635736bccb8d1f5d3e1dc35a1db26429b01337dc69148db89e712d23bc8c68196addf45c50a7f"
        + "f2893e84820314e86cd3c2166b5b85151f1ae248b3ab117e0527136b70b8a08b1d9351bd910612a7a9e72122f988e091"
        + "4e623fefcad6f082220d25af74973b981b3c5606af2cf8af40aea609c0a8a61499806a9fbea3b2d06a15bd8cbf3a0adf"
        + "0932380517af26c7c2c23c30a7a64e8bbb754b73409c6d720d2972bb68a3a2cff8429e498ebb7cc914a260c8779e2b65"
        + "86d15340c315e9d7582ed1b05c3a9fe63bbecf77bf453dd98bc204d5a0f07bfa07c6adde54c76a06e8c3172e5ea72af3"
        + "4c31301f4269d38cc4e34cb2aae57e5e9f2fe9e940763abda58856b2efbb4c8a49695a628e31fd84e64c9a712c2049a7"
        + "4b89659475de6e61da651d9eca9ab126d4a2cce23ee50a4e61a37c97895719515aca384fa8edcac458a615a29a543e6e"
        + "bea621bef75aa6524815a6fd4b7ccd4b202ac960231db48f21aa22cd7059286387f0fee168001936f964633ed07c83e1"
        + "48f12e174ed0adc2b77819cda79170b753cd8337acd9d4dfbb74866bf5baa94ec5c70af85dd760dcfcacd63ad7f2154d"
        + "9f81245466e4cc064297382653164f22c29cb8b501505e015eee4970f5326abdfda72613584cab044f0f5c2bc67c0d5a"
        + "cd4dc61fdb611111137046e5d10be6bb62024ab09a9c4f7246147e38155758e07345bfafa650f00500049e12eae56df0"
        + "26142f1baa3f285acf32b415cdf3424bff8cc692317a60e774e2671ee5551906b55fc76f70a58727825df10b1a8f5335"
        + "bca885ac7653deba3402ec7ce77c6f5897e40eef1a8f93d1e03797a3ad7acc8ce62466be62019e8af904e2f932aa4816"
        + "9efdd4216ae50be4d03b7f143f1c25c5",
      region: "usc1",
      provider: "gcp",
      endpoint: "https://directory-usc1.cello.mygentic.ai",
      peerId: "12D3KooWExQLMbvaioVqQCPkc1ZZgJ5kdoePymtMrg46ugMBs5zi",
      multiaddr: "/dns4/directory-usc1.cello.mygentic.ai/tcp/443/tls/ws",
      role: "validator",
    },
    {
      nodeId: "gcp-euw1",
      pubkey: "9cb77b68a98f49056fef232f4d56eeb9b66b1a6646fe06b966ff570a82ca6c14",
      mldsa_pubkey:
        "918cd17a64092e2678758d8d917c13e1055c2b16ee727b989d17f0dc9554b773b25bcc74e446bc5b7336f1c9cda507de"
        + "9f8d40d0577bcc968ce48157530d9e8fe6752461c948d9f2946ec59bca09d6bc41403004baef64b9319f6d458cd60153"
        + "a90a52884b4b66df01050fb183c2e41096bef3c35a183b2c7e953b75cbe665a73b57bdb47e43dbdae3c40f6d005418b9"
        + "0e9cfd17addee836768e422db56fcc103f2862ea3ce550e8298a25f32175b2ba2a3060f2d5064725dad47d5bf91e324e"
        + "94b3c6e9f1894a9474228adf86a207beaddf7ae0d0b2d746b05c083d8dbf188974213429c99161be4cfaa2cd07d1c3dd"
        + "74a2527fec9cfd4d6f159b3c20f5797b2d4295dd2dd462a59521a805c9bf241edde6da6801621ffdc765f1eef039c8bc"
        + "c6255ffe4704bebe24de55371c3ef44fc06a1abce25a1f44fe36f49a6b9b1455bd5aa9ffad9d727b4a0ba64bf5f9ad9f"
        + "ce76a0bf41e97e919ae32c83728acf046363cf84bbaa6d9f9e40e21cb8334d20bcd412533d92343d85867e5173a42ad7"
        + "d499ea86b7e20feeedef6c19190a3b509c3d9fe4e6522155f897802abf5a072d37f865ba7a581f9f3272aa1e3679b0ca"
        + "addeb2a53bfdebbe49f0f51bd4a1430a6a3936efb7b755aa98a6e1c34c0b6592f076c6cc2ba12ba8dad65b8d5db4062a"
        + "f3119310e0bae50465f282d38646c49839ab843a7e850c0dd960749df0ec048a38b5d4a2b119dea157b2347d4d0cba79"
        + "c1a1af604f79e305dfe2fc73431fd95d5948f888dbc759781e4106ca7c13acbcde7bc1ff2b0b421f8666f91c93b7ce11"
        + "027d9ad8a65ce0bbab4ace0876e47f29141e6a14c8639e4be0890c36b7da4f614c3499597598e9e4f72595a59a9598dd"
        + "c7ffd100f1c63e574eb0eec75b03682e3eb7d81b0682624d8b2f7d19f2e42124979eb2fa3d4a5e7a09aa872f80c6630e"
        + "9f6994e372afd76da4beee1f0baaaa398ea0d6aef33c34657c73eb081ecbccb086ca54bd905bd745b6baeda470d2de37"
        + "e2e8ac3deeff56e0240eeacf0f7ffbebfc4130dde15e2a12fdc9c4bea328f293f7dbe562c886e57656abade20e3a7895"
        + "291c115ac16dab24db1c75d490684f5936ed8ab15d85b18f91e6eca5e9ab22ed0596229b52e1f3ee616e436967228a9d"
        + "e328d8a937779d908caa13db628573df736d02903f6b90635bb95d8c1f2382637e75814e7c4ddb993dea4c038e5364f1"
        + "7af40c1762b909fd4053235df02eef5b8c61d81e52ce6dc028984c3c0a9e3836db47bf01d8db453a00159e4e64d44f48"
        + "d2299b602b9d507b2988d47fbc7907013c2a09efd0afe951a8e99fe705d5e0ddcf20c650601febcb41dded348eba855b"
        + "4e1871611cf202d3a8af367532dc322d59d2b5e2700eed7649b9d29181362774f296dee89e1655ae113aab978cf78365"
        + "3588501f28fce355bd31b18b92d98571850ac0203be4a9360227ff39d2944420108084e528d5b97c93161f27c8a1104a"
        + "b6de4aabfb3dd3f8a117759d8932e5aa88bf5461ee30008a9824558ecfb619836530cf47a761bce35c7ab7a7757ba275"
        + "568d1f1cb1243038aad5c6a462138f7ccfb264c21976ccf05df8f2ba0c2476f40a2d93583e32bf4af35de44fab6b8f03"
        + "036fec8d264dbf874b10ab1d97c4c78b8eaccde6690a606361dfb88830155fd7e4c62762f6047c9349895c95634495f3"
        + "f2b35909b0f7bf79de0eb7da895170b00da7d318f893fc27836dbd2d35da1cded6d3f1ac96f9e0a5ceb76b7a990508b5"
        + "72a4a7c1a1bab3d5b20b482b670fe4f3342b13bdf8fd150f61618bde09bbef34834841a22302a7549fdce00c029dd4dc"
        + "d125f2ee35df5c1ac73079ac958ce7b7",
      region: "euw1",
      provider: "gcp",
      endpoint: "https://directory-euw1.cello.mygentic.ai",
      peerId: "12D3KooWP52VSVrakyRdPyt23kAuhgp3FV6tiVRByfdyVvHAaEeJ",
      multiaddr: "/dns4/directory-euw1.cello.mygentic.ai/tcp/443/tls/ws",
      role: "validator",
    },
  ],
  // M10B / DOD-END-INGRESS-1 — the PORTAL INTAKE KEY. A submitting daemon seals its trust-signal
  // submission to this key so the DIRECTORY cannot read it. It has to be in the BUNDLED manifest and
  // not only in the served one, because a cold-boot daemon that cannot yet reach a directory falls
  // back to this constant.
  intake_key: { key_id: "intake-dev-1", pubkey: "87da56bf2ca5ef75d62d88dfed1f667f9fa565ee0a5306aeeef50f5d7053b3d1" },
  // M9D 004 — the portal's ML-KEM-768 intake public key, bound to `intake_key.key_id` by sitting beside it.
  mlkem_intake_key:
    "be175a20f3bca655cda82b344a5588d8540569b7464ee4c113408c6a051afbabadb7f2250bacab9cd6cd09860bf8d185"
    + "7d6aa3c73aa3cfc370cc574e1730c54aebb3ee744a872b0b39c02a014702b8a53845c52f827551e8dcc8080ba0afe9a3"
    + "36f32329b62eb0aa58540a46e6d92177a54fd06aa48c85495cf0737f271ef078313aa33e5ef4c008d93716290dd4a237"
    + "35ec75a4036b8e5bae8e59aa17c0ac49d59ab87cad8d16b96292cc732901a6e9c7d919cd62acba9427bce3f712bf88c3"
    + "e6e98be37321c25b21580201948454850258189382605ba13cc54a2e8925e816742b27122e161f79c62d54e11edef2b4"
    + "4564cf75ab8a4d9a7a6986123aa22e16d1c2ba57c6abb92566a574cfa3b51e545980f8b3707cc9652cad2d93555245aa"
    + "2597a814486d47859d96689cbd510702892bb5e074e92b090162a6e09764440566a8762138d25c7a251b526aaae48b92"
    + "ef5404e2284789a72601ea305386b322f0684e178cf984a6cda8b72b51100b39a155ca6de2e96d9e8522102900057acd"
    + "a97a50a5ca429dfa4babea54dfc8839e760cc2dc27ac8751c13259bfd9a17cf77bc1ba6b35a95a09133298b19ed04873"
    + "68e7adadc1b7e2c423417111242843ad49b7d74437155b2ba60b7ab67242b36311b7a293cde9729a681a98754f39374e"
    + "0b173842a326341c2508db21ce98332d14497df4b44ae2ae084ccf5f120ff1603c5d1a2f9eb8130f504cbaf480ffebc6"
    + "b7a045b8f8a5bec84c7eb17ead621a9af5a6acc071fdf00a584b0ae9825badec0000cb0da342aa42397ea00c29992a6b"
    + "6da327bda59662c365fcec2db5a52e1bf173703a023be5841b37c55a5731fdd3c73f5c5ee38124e9f9af8bc4c226d4a7"
    + "ccc70a0fd28f032066617317bcdbcada4473f40107f882453bcc5724224d90e30e98a00b544c85e40c7bba86c0417158"
    + "70bcb0d0836783bb1f45a40b009c772e63724da0904d60256ff8b685d774654b88e4373472aa962bd9a8980b14101c75"
    + "f58a98bfa274cd1900c4529b4cbc6daf5570dcb60a6c71cc55f0310e455173b285e16765df76500cb75fd5c4b9965200"
    + "bc686c75a53e0b4211d9f5ae0e20363fe46badc09d7c5673cde9a87303c4b212bfd28062354906d4749938f23cf3949f"
    + "8fc20972c066d5dc1210c80d9d5bcef559c68f60bf18423aeca97f5ee9b806531ee4355275800eabe2954831870cf361"
    + "4dcc48b9d44a86a0bb5ee81f6fa043dc964c135997adc2af74e26ea6d1a9ac084d0b339225f0c2da537a603c651d63ab"
    + "dd824638f69e9a9b69aed0b36923cdcc2ac9a3408f0ef57b92d31174b793d8abb6366a656b7420b5c40fc3392a45d347"
    + "b7e5648e52cfb9d6c3f3c575d84318a05bb07526c0dc82446f578f2c8c58aae958610004f5cb430b313a56b96dcda864"
    + "c0e30fffd95c56ac6fd2e6cf09b49693b292b846cad7c37d556a4c4b715359f577f89692cf165221c2cb1420ba79884a"
    + "b74ab51a165e81824d860985ef840d6422a8a6111b497281b0f77b9985ba6b42b7ea91ca4147612e6a975d48525f1109"
    + "a786b434900e27630368a1a8b140c49ac16a59ccc4e3471c3da82403d95e4f6a80a9da4bc271165715578eb07fd3488c"
    + "206a4385b8bae9892c4de6df7fd01af35b5ba443dd12e0c0b452728752d0c2e2",
  signatures: [
    { officerIndex: 0, signature:
      "9754ff387e7ec7c5a51afebd6174c1159463aee95c7a2af3350364b41f60a413461a5f0cb4fdb7e17932e0b5b9a4df7c"
      + "97e7767d70a3776dd8267d964c077307" },
  ],
  pq_signatures: [
    { officerIndex: 0, signature:
      "4828c85e8a6199c55171f6be7c9ea7e09640383e182650ed10b4b9613e36e0c9d61a54d1f5f8dfc35647e7525ed9c4be"
      + "2c5f377e1c5a4c9d07eb1cd843eb4b006e35e7289a39980a93ec01244f023395ae226808e327503a1d676fd847555677"
      + "17f91430f37d63ad81c9f113f3a598aa18495ee54feb756cccb7d7888f32655ca0ae4ef78b86e4e9de690becbd333b96"
      + "3ff37c19e93d85063909189ce7cc899f51c8c1b24ba166aac57740d6e5386b4db8c5dd1496efeff2c423af812dc992ee"
      + "60803149a092a0abd9f681175212baed8063ee0a52e2de67384893b3b3dbe59c67373865205d4143626d2269243ac259"
      + "d391877ce30795c8a926fc99fb2a3cae702f9bbec3f88bc66c95ae42109f5109b539b8564fcf35722d4e4e33fba827a9"
      + "9bfa834cc2c8d6b9264532e4cc87cbbc832e6cad6186dd08a61ba792877154d89aef115735f2ee4ca8b3b6df97dd6de6"
      + "3ff30e52c054269f3ad6e2dede40ac77cfbda89ceba200828fc7c609bc226f6ac946b0c30449c5f620edc0c9d5c20802"
      + "5f013575075d075544eb3b842a1750c6f4c1a89e7ec3bff34686915dfb14ee2a8139e1e0c902be2a5788794c6cdbc931"
      + "575cd950f548b88442a665cc6865e51059e6e685e01add87912773dd4bd389f884328629be8fbfc04fea8cd06813c610"
      + "dad03d7f08fec9ec62fb93024f8fa6aee913619f38d2e4cf0365d6c49c6b334d33b0e680abdd125fda3ff355dc4e6724"
      + "c2dcd37e85dcb0110c52b749fad4624fb763f227489986d7c9912cb12fe899d9605cfd182a038e1587ad8a9d6b0da269"
      + "1c0b2a32b27bd4a5eac77031c14fad5e649028816314cde8e970f7afb61347f6e94fb7dcd4312e3b8b49287100c7e0a0"
      + "b5ee4aa1e2ba678e059970f6c8231df1aded8905268f049cace1c599856d3c99a92a89d0878fb65bf61a148c59a51b8a"
      + "b64535f9b5fbde8cc50d386b11ee989589882492073ce0f35d510f68b14fb95ece576d39bc21575a0f43a9a9cdc85f59"
      + "d041aa2180976efcc62702e4240f52248ba472a0812cf74046aeeda94828dc5175e5e89f46ffb25e275d1dc6509289de"
      + "c434706fa82f62402951c858ce8c6fb4fbe98d69f3d2b2e527df2a8f68dfbf8c9cc867513141470bc6dded139ba44079"
      + "2d5342323a13fe62f3335a167f291eb6ca104ac9b6545163a04365aeb267d77a595c2012819961c118d7e1bbf02add45"
      + "d3894a7629a7376040b70e5ae9031f53d474cde9a40841676958729353114b7d6285fff1e8ef7d3d40edf876ee33b423"
      + "8760e13bd2d7b74ea18cb0363293746ae10342bb2139d08676c8f48cd8e26387b51d31b213198ee230d461148be00f91"
      + "342f85b12989074ebe517e3911312be4ea68793be082d11f0737067e51273fedc1413cbd957eb4a14ac12c3c6dc33974"
      + "17f83bef6e43c68e0d23fd57194a7e99a90f56ad86bbea62f441d860b44972663aa87dab52d996239f8c330d7f66a717"
      + "c9030f6ea332953842c5e816d4ada582133d05ce86c31b3614dac075738296d6942240ea2f2137a213c9838db9f79aca"
      + "4b80aa1363b38a7760db88e22e26f1868a71a24c8e31a53339b103f81054b3ac550e06eb19b13c5b854626eb6955eb53"
      + "b071e6fac987f5425262029a6cad1080c5699fddaee439846e685468e3e441a7e9496dfabc0758ff2ca58d56d733fbb2"
      + "c80ee3df45c39e67da5a3c27a97e31262ec46aa65e6b0f5d5c1040f6d3c5f93c4d45760f2a656413bc1be2b0ff601652"
      + "d468a9b4b60dc9323b58875ce3e6813483c6b16e792d589cf08756591d879a4b652cf61ee74dcb4d01fbd9c524a1a59d"
      + "03ee66f8fe60c6c50ed68a680ce5dda148f7a93d3b5c10ba1b8ea3735fa1f43afe38d29f5f57127254f6490fa7a65e9d"
      + "54123c5cecda554085d6b31328940d8c1702845d97984f625ef8a7b49e5d8e30f6ca14ac156ef233eaf3ed88d800e25e"
      + "598668b3d30c358a875bc2c837d5ccfe0e072f36d33ccaaebcbfd2397096f84bdda7e016f443c92954476ca03fb3a40e"
      + "ca9911ebd2dfa6269b986d4c4c2c344df14e516d54ac1fb14277eff46155fe50d480a854e408135c3e3d12f96f4ed50f"
      + "d7b41901d34a059f2a9096f8046d018b6aac47c48428a2ae3d96f8989ddb4225d5471fa6aae597f83377cb0d05e82250"
      + "b4f8e4bb6b91ac58839f9fadc45def36d813d5e33f0611d270b56a0096d057e0ffe0b50dd956bacdf963ee268d7dac67"
      + "d498e62dfc94b41b5b08a413e50e155675f4ca3021336b540b9528e14f83c92ba73b4dd0ff0e6ec9a0a2c7cc231e2479"
      + "6cc48c44c9f137840037b32c54b8fc16cb2e4c90afced4bfbfba665bc45c8b958a1bc81c4b3cceccf796fa4bde6aabbf"
      + "dfa8f1e9832a752b5cdf8a04740f0ce82e2b94c4117f966e34ed66bcd5bb9b612c424ad92f80254f23e0f9edf0b5a402"
      + "ce790d16fe04bfa5bfbc7fc15f7b9465a24c0b18afe075b4a7d200c4bea71f420caba58339bd7f9fa56a2c6d8c5bcb35"
      + "c9cc82e41acb3ee11cd24df4e616865ed691c6385af9fd62337e96f6a6595a3ec12b14ce6c070c521e9148b699927435"
      + "766c71f3784e11466de6e337e6d2cdfbf2fa386bd7f5df1ca34b1a60ffd8d2838fabc338bee0904064c96bf1bbb0cd91"
      + "3e0a7d43c884736c13d2454a0f9c401d5e05ce62f52e8dfc356e01fc5d843ca6ea01ebeed503fa63291ac2297c55b265"
      + "199d5189ee9fa5c26dced19042c77f318658a3f673afe262ea91ed06e6054ee6aa8e6f5bb94ca13238baaa227d1e8716"
      + "e4a2ff39c25a2537379504478b5076e8a42653d6d93afdbd137ed38783813aae643210b9a26e0db4ca7c5fb6c701c5e4"
      + "08381ee6b256a5200339a858c04b0b2175feed41d21e231fb24a4d4fba1f505412c65f262661719970ce5b51a813c3ed"
      + "35c31b8d138d96fc36438fc7e49582887eb491bb632695b1cc36216a912d59ad187e067f5151d9f9cd611eb8b50811b6"
      + "c483fdcdc80e83e17d4686e693ac0a7cbed37e7b96f2a14da055196692624d52b1dcfe7a72d680bfc6a257a7957ec703"
      + "d88b511ba2408f659630c24287020f634918b10ada603c590f1bcd74dc9c175f3de219de43955f9740ff01fd54102061"
      + "d7861a05c855378f71ce9b4118c519e2cc0936a905be6cdcdbe1d6e1ac86e9e09d6bae0104923ee18eeaa7fa6a48e881"
      + "06b2a15191931f826bca04dba0a82132e890f60e43d4affc9eee8b3524109bacb33d29e9801d1c879356704cb64da99b"
      + "306dac678c8db13489dc84f50a312ccd2a51827c8f45cdcd8dc4163382b879c00228323439507578989ca9bfc4cce5f0"
      + "fb08262b3a434a4e50515b5c7d87aabdc5d8e6171931364d6063647888959ca4c3d3d4fb040b26373b4465838790a1a9"
      + "b0b3b6c0c5d2d4fb000000000000000011233448" },
  ],
};

/**
 * Pinned consortium officer root public key(s). Officer 0's Ed25519 public key (hex). The client
 * verifies BUNDLED_CONSORTIUM_MANIFEST's Ed25519 signatures against this set. Public data.
 */
export const BUNDLED_CONSORTIUM_ROOT_KEYS: readonly string[] = [
  "e8300a2b9de7be6f6d629f778dc319715ad0010c0639f3a1564181d56d3eb104",
];

/** Minimum number of distinct valid officer signatures required (dev: single officer, threshold 1). */
export const BUNDLED_CONSORTIUM_THRESHOLD = 1;

/**
 * M9D 004 (D22) — the pinned ML-DSA-44 officer root(s). Officer 0's public key, derived from
 * `cello-consortium-officer-mldsa-key-0`. The client verifies BUNDLED_CONSORTIUM_MANIFEST's
 * `pq_signatures` against this set, and requires them. Public data.
 */
export const BUNDLED_CONSORTIUM_ROOT_KEYS_PQ: readonly string[] = [
  "1d309380852c4319812480d9a2b3b536957c4a5e3abf35799ef85a98179695748d32810d53f929a368062fcbf526fbef"
  + "529ff8dea3a5435981c24b7561a78c90ed4bd5e7654da8e3d0f51a84fb135327223ce0d2aaed8293a08b753f1bee662f"
  + "b23b9ddad12315942a3fcd6dbacaa4ad7928ba55aa057a1d771297ec6b5b643801f2b892dbfde96bbf1d9789ac40594d"
  + "64754fd7d86140088240cc1d9dbc3143cabd7394ab5ee8f50dc5f3377e3bd9d627a4fd59b355e51b2554ec022ba52594"
  + "e22e5379a20e9146bc5edde0b31334992f4d58eb93a2a2bacacb01b1cbf0445dd4961d61ce073c17184859e50f4e5b61"
  + "c3338c6000b5e184a21b4affd99dada374c3b2f9a2ed4e08457043f7071e9c2becd423fb2bbef2ca944c88c0a99df28f"
  + "02b6ec49ac4ca416c118b2c5ddb9b93038c8317155ec66340e1c4862bf23edab1ad950c080fd4471405bfe579a09fda3"
  + "5cc693d1b567eb3a27421410ae209e5c98718ecbfebb55a82002b504cb3748a0a76634d45896b479702ecb1b0e44e593"
  + "3385a486bd49dbc4a4d542144e078422b6b846ff7784c81e817155625ec306d56f8b753c0595a66441995e0b4dcea5e3"
  + "9096ebba3ebea25b807aca9cd122b21fa2a3eddfa82e4f87ee6bac08d764574637fea9f769964d25f0d7b335546e8b37"
  + "e1c7e99baa31586bf5dd917e33fe94b98200e6d33e0db7407fd0bbe9fc12a977cba4cd7fd448d7050a39afa101db4a09"
  + "76b6953774e9ba1ae3db02990368c79f369d63dc7b4acb81ba7517bf899289b469cd4d83687d29738ac3d5b4d34da7bc"
  + "9f9f2bec9d13e30dea49d516aaa127a39afe2718d5f1f8477bf4e9935f7bf972f65fdca5cc8895e0b12e0871992587fc"
  + "8e36430a922c17d473f6ae6ec3e1fff4cbb7a355e2ac686b25b1690f4c76a5034783c8781d80113ee88ec0e8f42d817d"
  + "8dfa9d508b3989b08df999056a859023d4e4329e29d1a6d55d0669c4a7b6b9aa3e39bac85e23697559469ca637469460"
  + "ffc28776a432802648c6c31acba9ac4e47d51dea52a2f87737d4278280e3014737647e72853183e99eb223c5bddb7e41"
  + "09f555ef4bbbd87bb7f6802bf79e404d7924bf04a3956782ade36dbac720198e17332b99bac7ad1939be26e9611cde62"
  + "06f2d27e2ba0e5ba20cc0f1958c99825ec0c6a2d55f9078e352c8ecb0491a010a60c2fc6b0e944bac9d5c1e79610bc10"
  + "2e89eb36fd4ef176a095b36bf4d8d497abaf9d2c365fa34ba9a3fa260620af760795484f9c038d54c6e998df71aae44e"
  + "19fc441dc440e915aee45ce9001290f6caef7f350ddc1ee577e82430fcb7645dfa9668d285e4beb1adefdc6e8c8fcf8a"
  + "cb2c40afde3105d926912c211d87ea48859292c99f243d4086e89b0116fb01fe6d6e52494da0aaff6b14e63f91b79f07"
  + "6a7fb7282ed8c44fc201ff3099a35b1aea4b276f406f13baf43decb6d976f6d6b753035772dae5d32cf222ff8471c785"
  + "6a79e4e636263c96ef7f695e0d8f8c3d0f0ca84d6dc3461103bec0d0be0f8a3b5ed02957a8f6465bd723f2edc41c1426"
  + "7b5179240517e40d0c1d8fad3b78988d3fc8117601749f6cb2dbd8dfab5eec4f8851b508d308e3250a87a4705b270ce9"
  + "b075d07e7771dde00ce26929cfb8d8e84d11aff5e23256eb47b2d8d7fe1994f99653475fed8896f2678713c0d6dfd8b9"
  + "09efe6dc950ab2dab33d409b0607a32df1ef4674564ef0a801846381527fc734902720b446483fc1dc7a80f5e2c953cf"
  + "bda2eaa919708a7d3be516898dcbee30aa6428c4bbd109c6ca8f40cbe387fc3429b8016c5664d104b0072d433fd4af3a"
  + "b9a257fc3288f87955798f81d6b5cded",
];

/** Minimum distinct valid ML-DSA officer signatures (dev: single officer, threshold 1). */
export const BUNDLED_CONSORTIUM_PQ_THRESHOLD = 1;
