/**
 * FINDING-4 — the bundled consortium roster (sovereign-node REDUNDANCY invariant).
 *
 * This is the signed list of the sovereign directory nodes that make up the CELLO consortium,
 * COMPILED INTO the client. It is loaded by default (when the operator does not override it via
 * CELLO_CONSORTIUM_MANIFEST) so that a cold-boot daemon already knows every directory — and can
 * fail over to a reachable one — even when its configured/primary directory is unreachable. Without
 * a bundled roster the failover resolver has nothing to route to (the exact FINDING-4 gap: the
 * roster-aware dialer was correct but the roster was empty), so a single directory being down
 * stranded the client at startup, violating the redundancy invariant.
 *
 * Trust model:
 *   - The manifest is threshold-signed by the consortium officer key(s). At load the client
 *     RE-VERIFIES it against BUNDLED_CONSORTIUM_ROOT_KEYS (a self-consistency / anti-corruption
 *     gate — the manifest and root keys ship together, so this catches a bad regeneration, not a
 *     network adversary).
 *   - The node `pubkey`s are the directories' Ed25519 node keys. They are the trust anchor for
 *     step-6 directory identity auth (M7-MANIFEST-002): when the client connects to (or fails over
 *     to) a directory, the directory must sign the client's challenge with the matching node key,
 *     proving it is the real consortium node for that nodeId — defeating a MITM on the plaintext
 *     /bootstrap that would otherwise redirect the client to a rogue directory. THIS is the
 *     adversarial defense; it is enabled by default alongside the roster.
 *
 * nodeId MUST equal the directory's reported NODE_ID (`<cloud>-<region>`, e.g. `gcp-use1`); the step-6 verifier
 * looks the node up by nodeId. pubkey MUST equal the node's own Ed25519 signing key, which the
 * regeneration script below reads from GCP Secret Manager (`cello-<nodeId>-node-key`) rather than
 * being transcribed. endpoint is the HTTP /bootstrap base, and MUST be the node's ADDRESS — see
 * PRODUCTION_DIRECTORY_URL in directory-bootstrap.ts for why a hostname here disables step-6.
 *
 * Regeneration: on directory node-key or officer-key rotation, re-sign with
 * `infra/scripts/sign-gcp-consortium-manifest.mjs` (in the trustless-cello repo) and update this
 * constant + BUNDLED_CONSORTIUM_ROOT_KEYS. The officer signing key lives in GCP Secret Manager as
 * `cello-consortium-officer-key-0`; only its PUBLIC key is embedded here.
 *
 * Crypto reference: RFC 8032 (Ed25519 threshold signatures, verified by verifyManifest).
 */

import type { ConsortiumManifestInput } from "@cello-protocol/crypto";

/** The signed consortium manifest (roster of sovereign directory nodes). */
export const BUNDLED_CONSORTIUM_MANIFEST: ConsortiumManifestInput = {
  // ── v3, the TLS cutover (2026-09-10) ────────────────────────────────────────────────────────
  // Every endpoint moved from `http://<raw ip>:9090` to `https://directory-<region>.cello.mygentic.ai`,
  // terminated by that region's own load balancer, and every multiaddr from `/ip4/…/tcp/8080/ws` to
  // `/dns4/…/tcp/443/tls/ws`. Proven against the running fleet before shipping: a real libp2p node
  // dialled all three balancers over WSS and got Noise + yamux with the expected peer id.
  //
  // 🔴 THIS ROSTER AND THE ONE THE NODES SERVE MUST CARRY THE SAME ENDPOINTS. The daemon builds its
  // directory-identity challenge verifier ONLY when the resolved directory URL matches one of the
  // endpoints BELOW. If the fleet serves a name this file does not list, step 6 does not fail — it
  // is skipped, silently, on every connect and reconnect, and step 6 is what turns a /bootstrap
  // MITM into a refused connection rather than a successful impersonation.
  //
  // `version` is a MONOTONICITY GATE, not a schema number: the daemon persists the highest version
  // it has seen and rejects anything lower as a rollback. So a daemon carrying this v3 will refuse
  // a fleet still serving v2 — which is why the two move together, and why this must only ever
  // increase.
  //
  // Generated by trustless-cello/infra/scripts/sign-gcp-consortium-manifest.mjs. Do NOT hand-edit
  // a field: the signature covers every one of them and an edited copy verifies against nothing.
  version: 3,
  not_before: "2026-01-01T00:00:00Z",
  expires: "2030-01-01T00:00:00Z",
  nodes: [
    {
      nodeId: "gcp-use1",
      pubkey: "7969e22a7d95293ae343cb2667c2a4d7127aa8748478582fa637674c30e0113c",
      region: "use1",
      provider: "gcp",
      endpoint: "https://directory-use1.cello.mygentic.ai",
      peerId: "12D3KooWMH58hm8xpuwgwaNSvnvXBuc126jfuUMVbrGNcU2MeEAX",
      multiaddr: "/dns4/directory-use1.cello.mygentic.ai/tcp/443/tls/ws",
      role: "validator",
    },
    {
      nodeId: "gcp-usc1",
      pubkey: "ef961384100bb087f36b68e3a270acb8f22fdf62c4cd5e517e423afb7f399002",
      region: "usc1",
      provider: "gcp",
      endpoint: "https://directory-usc1.cello.mygentic.ai",
      peerId: "12D3KooWExQLMbvaioVqQCPkc1ZZgJ5kdoePymtMrg46ugMBs5zi",
      multiaddr: "/dns4/directory-usc1.cello.mygentic.ai/tcp/443/tls/ws",
      role: "validator",
    },
    {
      nodeId: "gcp-euw1",
      pubkey: "9cb77b68a98f49056fef232f4d56eeb9b66b1a6646fe06b966ff570a82ca6c14",
      region: "euw1",
      provider: "gcp",
      endpoint: "https://directory-euw1.cello.mygentic.ai",
      peerId: "12D3KooWP52VSVrakyRdPyt23kAuhgp3FV6tiVRByfdyVvHAaEeJ",
      multiaddr: "/dns4/directory-euw1.cello.mygentic.ai/tcp/443/tls/ws",
      role: "validator",
    },
  ],
  // M10B / DOD-END-INGRESS-1 — the PORTAL INTAKE KEY. A submitting daemon seals its trust-signal
  // submission to this key so the DIRECTORY cannot read it; without it `cello_attestations_issue`
  // refuses with `intake_key_absent` rather than sending in the clear. It has to be in the BUNDLED
  // manifest and not only in the served one, because a cold-boot daemon that cannot yet reach a
  // directory falls back to this constant — and "your first submission fails until you have polled"
  // is indistinguishable from the feature being broken.
  intake_key: { key_id: "intake-dev-1", pubkey: "87da56bf2ca5ef75d62d88dfed1f667f9fa565ee0a5306aeeef50f5d7053b3d1" },
  signatures: [
    {
      officerIndex: 0,
      signature:
        "537de3ac39d6a5f261d576c8938e788b46d587b282be5e0166c5d7fad6dac55efed003277c5625d1b5930c328d0eb41044e8e7de7ea31a1021b22e7133317f09",
    },
  ],
};

/**
 * Pinned consortium officer root public key(s). Officer 0's Ed25519 public key (hex). The client
 * verifies BUNDLED_CONSORTIUM_MANIFEST's threshold signatures against this set. Public data.
 */
export const BUNDLED_CONSORTIUM_ROOT_KEYS: readonly string[] = [
  "e8300a2b9de7be6f6d629f778dc319715ad0010c0639f3a1564181d56d3eb104",
];

/** Minimum number of distinct valid officer signatures required (dev: single officer, threshold 1). */
export const BUNDLED_CONSORTIUM_THRESHOLD = 1;
